### ISSUE TITLE
jTab possibly breaking Toggl Track obsidian plugin

### ISSUE THREAD

**Issue by nschutz** [davfive/obsidian-jtab#10]
Toggl Track Queries Cannot Be Parsed: "match[i].replace is not a function"

![image](https://user-images.githubusercontent.com/30931746/206021735-faa2d806-ae4b-4427-bf00-b506bb30d53f.png)

After some trials I ended up disabling each of my community plugins one by one, disabling jtab fixed my issue.

Please let me know if anyone else is seeing this issue, I know there's probably only a couple people out there affected by this. Thanks!

**Comment by davfive** [comment]
I've used Toggle before. I'll install the Toggl plugin and see if I can reproduce this and track down the problem sometime this week.

**Comment by davfive** [comment]
This issue has been fixed and is included in the v1.2.3 package release. Download or update it in Obsidian Settings under Community Plugins.
