### ISSUE TITLE
Solution to make this plugin "responsive"

### ISSUE THREAD

**Issue by WinnerWind** [davfive/obsidian-jtab#22]
I'm not a master programmer, but here's how I'd code to automatically insert a line break (hence starting a new "tab line" once a limit is reached.)

1. Starting from the left, start counting each note. Each note can be defined as a
- Single number (without $)
- A note connected to a number with a period (So x.y)
- Multiple numbers not seperated by a space 
- Numbers seperated by a slash character
- Chord definitions

2. Set a limit for how many notes can be on one line based on the editor width, or by asking the user for the number of notes in a single line.
3. Keep going to the next note, keeping in mind the current note no. that increments every time we go to the next note, and making sure it doesn't exceed the set limit.
4. Add a line break once that set limit is reached, and set the counter to zero, then keep going.

Of course, I'm not a programmer, this is just how I'd do it using pseudo code. It would be great to finally have a responsive, themed tabature plugin for Obsidian.

**Comment by davfive** [comment]
@WinnerWind , thanks for the suggestion. 

While I agree this would be cool, my library is a "wrapper" around jTab to allow it to be used in Obsidian. The jTab authors haven't updated their code in years. I have made some modifications to the under library (and have my own fork for this project), however, the changes have been mainly to fix bugs (and an upcoming one to convert it to typescript). I haven't had any plans to "modernize" it with aria/responsive/etc type stuff though. That would basically require me to do a full rewrite - which is beyond my current aspirations for this library.

**Comment by WinnerWind** [comment]
Understandable. I just wish that the default JTAB repo was kept up to date. I sent an issue request a long time ago and it has yet to get a reply, but I guess we have to play with the hand we are dealt with. I fully respect your decision though.
